name: deploy_frontend


on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZUREKEY }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite true --account-name azureresumest --auth-mode key -d '$web' -s frontend/
    

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()